/**
 * The block comment a generated TypeScript file opens with: the twin of
 * the line-comment header every other language gets, in the comment
 * form TypeScript tooling reads. It carries the command that reproduces
 * the file. The target is named because one of the four TypeScript
 * targets is the default, so a command that omitted it would regenerate
 * a web project's file for react-native; the code directory is named
 * because every run has to name one.
 *
 * It also asks formatters to leave the file alone - a generated file
 * cannot match everyone's quote style, and every run replaces it whole,
 * so a formatter can only create diffs.
 */

import type { RenderHeaderCommentArgs } from '../types/typescript';

import { CUSTOM_EVENT_TYPE_NAME_BY_TYPE } from '../../events/customEventType';
import { EVENT_LIST_HEADING } from '../lineCommentHeader';

function renderHeaderComment({ events, target }: RenderHeaderCommentArgs): string {
  const body =
    events.length === 0
      ? ' *   (no events defined)'
      : events
          .map(
            (event) =>
              ` *   ${event.id}  ${event.name}  (${CUSTOM_EVENT_TYPE_NAME_BY_TYPE[event.type]})`,
          )
          .join('\n');
  return [
    '/**',
    ' * AUTO-GENERATED by @keewano/codegen.',
    ` * DO NOT EDIT. Re-run \`npx keewano-codegen --target ${target} --code <directory of this file>\` to regenerate.`,
    ' * Formatters and linters should skip it (.prettierignore, .eslintignore).',
    ' *',
    ` * ${EVENT_LIST_HEADING}`,
    body,
    ' */',
  ].join('\n');
}

export { renderHeaderComment };
