// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target kotlin --code <directory of this file> --asset <assets directory>` to regenerate.
// Formatters and linters should skip it (.editorconfig, detekt, ktlint).
//
// Events, in declaration order (id = 2500 + position):
//   2500  Event00  (None)

package com.keewano.sdk.generated

import com.keewano.sdk.KeewanoCodegen
import com.keewano.sdk.KeewanoSDK

fun KeewanoSDK.reportEvent00() = KeewanoCodegen.reportCustomEvent(2500)
