# AUTO-GENERATED by @keewano/codegen.
# DO NOT EDIT. Re-run `keewano-codegen --target python --code <directory of this file>` to regenerate.
# Formatters and linters should skip it (black, ruff, flake8).
#
# Events, in declaration order (id = 2500 + position):
#   2500  Event00  (None)

from keewano_sdk import CustomEventSet, KeewanoCodegen

CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(
    version=2673883758,
    event_count=1,
    gzip_base64="H4sIAAAAAAAA/zvCye5alppXYmDAwAAA9Yi+fAwAAAA=",
)


def report_event00() -> None:
    KeewanoCodegen.report_custom_event(2500)
