/**
 * AUTO-GENERATED by @keewano/codegen.
 * DO NOT EDIT. Re-run `npx keewano-codegen --target react-native --code <directory of this file>` to regenerate.
 * Formatters and linters should skip it (.prettierignore, .eslintignore).
 *
 * Events, in declaration order (id = 2500 + position):
 *   2500  Event00  (None)
 */

import type { CustomEventSet } from '@keewano/react-native-sdk';

import { Keewano } from '@keewano/react-native-sdk';

export function reportEvent00(): void {
  Keewano.reportCustomEvent({ name: 'Event00' });
}

export const customEventSet: CustomEventSet = {
  version: 0x9F603A6E,
  eventCount: 1,
  gzipData: new Uint8Array([0x1F, 0x8B, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x3B, 0xC2, 0xC9, 0xEE, 0x5A, 0x96, 0x9A, 0x57, 0x62, 0x60, 0xC0, 0xC0, 0x00, 0x00, 0xF5, 0x88, 0xBE, 0x7C, 0x0C, 0x00, 0x00, 0x00]),
  events: [
    { id: 2500, name: 'Event00', type: 0 },
  ],
};
