// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target swift --code <directory of this file>` to regenerate.
// Formatters and linters should skip it (.swiftformat, .swiftlint.yml).
//
// Events, in declaration order (id = 2500 + position):
//   2500  Event00  (None)

import KeewanoSDK

public enum KeewanoCustomEvents {
    public static let set = KeewanoCustomEventSet(
        version: 2673883758,
        eventCount: 1,
        gzipBase64: "H4sIAAAAAAAA/zvCye5alppXYmDAwAAA9Yi+fAwAAAA="
    )
}

extension KeewanoSDK {
    public static func reportEvent00() {
        KeewanoCodegen.reportCustomEvent(2500)
    }
}
