/**
 * The Python target: one bridge entry point per payload type instead of
 * overloads, snake_case wrapper names, and the set built through
 * `from_gzip_base64` - the seam docs/custom-events.md in the Python SDK
 * specifies.
 */

import type { CustomEventTypeValue } from '../../events/customEventType';

import { ungzip } from 'pako';

import { makeEvent } from '../../events/__tests__/helpers/definitionsFile';
import { buildCustomEventSet } from '../../set/buildCustomEventSet';
import { emitGeneratedSource } from '../emit';

/** [payload type, the wrapper's signature, what reaches the bridge]. */
const PAYLOADS: readonly [CustomEventTypeValue, string, string][] = [
  [0, 'report_tap()', 'report_custom_event(2500)'],
  [1, 'report_tap(value: str)', 'report_custom_event_str(2500, value)'],
  [2, 'report_tap(value: int)', 'report_custom_event_uint(2500, value)'],
  [3, 'report_tap(value: bool)', 'report_custom_event_bool(2500, value)'],
  [4, 'report_tap(value: int)', 'report_custom_event_uint(2500, value)'],
  [5, 'report_tap(x: int, y: int)', 'report_custom_event_ushort_pair(2500, x, y)'],
  [6, 'report_tap(value: int)', 'report_custom_event_uint(2500, value)'],
];

const emitPython = (type: CustomEventTypeValue): string =>
  emitGeneratedSource({
    events: [makeEvent({ name: 'Tap', type, indexOffset: 0 })],
    target: 'python',
  });

describe('the Python target: wrappers', () => {
  it.each(PAYLOADS)('payload type %i takes %s', (type, signature, call) => {
    const source = emitPython(type);
    expect(source).toContain(`def ${signature} -> None:`);
    expect(source).toContain(`KeewanoCodegen.${call}`);
  });

  it.each([
    ['EnemyKilled', 'report_enemy_killed'],
    ['EnterMainLevel', 'report_enter_main_level'],
    ['Event00', 'report_event00'],
    ['USDPrice', 'report_usd_price'],
  ])('spells the wrapper for %s as %s, the way the contract example does', (name, wrapper) => {
    const source = emitGeneratedSource({
      events: [makeEvent({ name, type: 0, indexOffset: 0 })],
      target: 'python',
    });
    expect(source).toContain(`def ${wrapper}() -> None:`);
  });

  it('imports only the set type when there are no wrappers to call the bridge', () => {
    /**
     * The host lints the generated file with its own settings, and an
     * unused KeewanoCodegen import it was told never to edit would flag
     * there.
     */
    const source = emitGeneratedSource({ events: [], target: 'python' });
    expect(source).toContain('from keewano_sdk import CustomEventSet\n');
    expect(source).not.toContain('KeewanoCodegen');
    expect(source).toContain('# (no custom events declared yet)');
  });
});

describe('the Python target: the set', () => {
  it('carries the map as base64 that decodes back to the built bytes', () => {
    const events = [makeEvent({ name: 'Tap', type: 1, indexOffset: 0 })];
    const built = buildCustomEventSet(events);
    const source = emitGeneratedSource({ events, target: 'python' });

    const base64 = /gzip_base64="([^"]+)"/.exec(source)?.[1] ?? '';
    expect(Buffer.from(base64, 'base64')).toEqual(Buffer.from(built.gzipData));
    expect(ungzip(Buffer.from(base64, 'base64'))).toEqual(ungzip(built.gzipData));
    expect(source).toContain('CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(');
    expect(source).toContain(`version=${String(built.version)},`);
    expect(source).toContain('event_count=1,');
  });

  it('still exports the set for an empty event list, version 0 as the contract spells "none"', () => {
    const source = emitGeneratedSource({ events: [], target: 'python' });
    expect(source).toContain('version=0,');
    expect(source).toContain('event_count=0,');
    expect(source).toContain('gzip_base64="",');
  });
});

describe('the Python target: the file', () => {
  it('opens with a # header naming the regenerate command and the events', () => {
    const source = emitPython(1);
    expect(source.startsWith('# AUTO-GENERATED by @keewano/codegen.')).toBe(true);
    expect(source).toContain('# DO NOT EDIT. Re-run `keewano-codegen --target python');
    expect(source).toContain('#   2500  Tap  (String)');
  });

  it('separates top-level definitions with two blank lines, as PEP 8 asks', () => {
    const source = emitGeneratedSource({
      events: [
        makeEvent({ name: 'First', type: 0, indexOffset: 0 }),
        makeEvent({ name: 'Second', type: 0, indexOffset: 1 }),
      ],
      target: 'python',
    });
    expect(source).toContain(')\n\n\ndef report_first');
    expect(source).toContain('(2500)\n\n\ndef report_second');
  });
});
