/**
 * Generated-source layout: the header comment, the per-type wrapper
 * signature table and the wrapper bodies.
 */

import { makeEvent } from '../../events/__tests__/helpers/definitionsFile';
import { emitGeneratedSource } from '../emit';

describe('emitGeneratedSource: header + scaffolding', () => {
  it('emits the AUTO-GENERATED warning + DO NOT EDIT line at the top', () => {
    const source = emitGeneratedSource({ events: [] });
    expect(source.startsWith('/**')).toBe(true);
    expect(source).toMatch(/AUTO-GENERATED by @keewano\/codegen/);
    expect(source).toMatch(/DO NOT EDIT/);
  });

  it('imports `CustomEventSet` from the SDK module', () => {
    const source = emitGeneratedSource({ events: [] });
    expect(source).toMatch(/import type \{ CustomEventSet \} from '@keewano\/react-native-sdk'/);
  });

  it('targets @keewano/react-native-expo-sdk for the `expo` target', () => {
    const source = emitGeneratedSource({
      events: [makeEvent({ name: 'Tap', type: 0, indexOffset: 0 })],
      target: 'expo',
    });
    expect(source).toMatch(
      /import type \{ CustomEventSet \} from '@keewano\/react-native-expo-sdk'/,
    );
    expect(source).toMatch(/import \{ Keewano \} from '@keewano\/react-native-expo-sdk'/);
    expect(source).toMatch(/Keewano\.reportCustomEvent/);
  });

  it('lists every event id + name + human-readable type in the header comment', () => {
    const source = emitGeneratedSource({
      events: [
        makeEvent({ name: 'AlphaEvent', type: 1, indexOffset: 0 }),
        makeEvent({ name: 'BetaEvent', type: 5, indexOffset: 1 }),
      ],
    });
    expect(source).toContain(' *   2500  AlphaEvent  (String)');
    expect(source).toContain(' *   2501  BetaEvent  (UnsignedShortVec2)');
  });

  it('notes "(no events defined)" in the header when the event list is empty', () => {
    expect(emitGeneratedSource({ events: [] })).toMatch(/no events defined/);
  });
});

describe('emitGeneratedSource: per-type signature table', () => {
  it('renders the correct method signature for every CustomEventType', () => {
    const source = emitGeneratedSource({
      events: [
        makeEvent({ name: 'Bell', type: 3, indexOffset: 0 }),
        makeEvent({ name: 'Card', type: 6, indexOffset: 1 }),
        makeEvent({ name: 'FirstSlot', type: 0, indexOffset: 2 }),
        makeEvent({ name: 'NameStr', type: 1, indexOffset: 3 }),
        makeEvent({ name: 'PointVec', type: 5, indexOffset: 4 }),
        makeEvent({ name: 'Score', type: 2, indexOffset: 5 }),
        makeEvent({ name: 'When', type: 4, indexOffset: 6 }),
      ],
    });
    expect(source).toMatch(/reportBell\(value: boolean\): void/);
    expect(source).toMatch(/reportCard\(value: number\): void/);
    expect(source).toMatch(/reportFirstSlot\(\): void/);
    expect(source).toMatch(/reportNameStr\(value: string\): void/);
    expect(source).toMatch(/reportPointVec\(value: \{ x: number; y: number \}\): void/);
    expect(source).toMatch(/reportScore\(value: number\): void/);
    expect(source).toMatch(/reportWhen\(value: Date\): void/);
  });

  it('preserves the PascalCase first letter when composing the method id', () => {
    const source = emitGeneratedSource({
      events: [makeEvent({ name: 'BestScore', type: 2, indexOffset: 0 })],
    });
    expect(source).toMatch(/reportBestScore/);
    expect(source).not.toMatch(/reportbestscore/);
  });
});

describe('emitGeneratedSource: wrapper functions', () => {
  it('exports a report wrapper that forwards a None event by name only', () => {
    const source = emitGeneratedSource({
      events: [makeEvent({ name: 'Tap', type: 0, indexOffset: 0 })],
    });
    expect(source).toMatch(/import \{ Keewano \} from '@keewano\/react-native-sdk'/);
    expect(source).toMatch(/export function reportTap\(\): void \{/);
    expect(source).toMatch(/Keewano\.reportCustomEvent\(\{ name: 'Tap' \}\)/);
  });

  it('forwards the value argument for a typed event', () => {
    const source = emitGeneratedSource({
      events: [makeEvent({ name: 'Score', type: 2, indexOffset: 0 })],
    });
    expect(source).toMatch(/export function reportScore\(value: number\): void \{/);
    expect(source).toMatch(/Keewano\.reportCustomEvent\(\{ name: 'Score', value \}\)/);
  });

  it('emits a placeholder comment when no events are declared', () => {
    expect(emitGeneratedSource({ events: [] })).toMatch(/no custom events declared yet/);
  });
});
