/**
 * The header a generated file opens with, for every emitter that builds
 * one out of line comments - which is all of them but TypeScript, whose
 * own header is a block comment. The prefix is the caller's: `//` unless
 * it says otherwise, and Python says `#`. It says three things a reader of a
 * generated file needs: what wrote it, the command that regenerates it -
 * target included, so rerunning in another project cannot quietly emit
 * for the default one - and that formatters should leave it alone,
 * since every run replaces the file whole.
 *
 * The command names the target and the directories a run cannot omit -
 * the code directory, and the asset directory for the target whose SDK
 * reads one - not the whole invocation: a project whose definitions file
 * is not at the default path adds `--input` itself.
 *
 * Shared rather than copied per language: the wording is the same
 * promise in each, and a copy would drift the moment one of them is
 * corrected.
 */

import type { LineCommentHeaderArgs } from './types/lineCommentHeader';
import type { ParsedEvent } from '../events/types/event';

import { CUSTOM_EVENT_TYPE_NAME_BY_TYPE, FIRST_CUSTOM_EVENT_ID } from '../events/customEventType';

/**
 * The line above the event list, for every header: it states the
 * numbering rule with the constant the parser applies, so the two cannot
 * say different numbers.
 */
const EVENT_LIST_HEADING = `Events, in declaration order (id = ${String(FIRST_CUSTOM_EVENT_ID)} + position):`;

/**
 * What a generated file says when the project has declared no events
 * yet. Every emitter says it, byte for byte apart from its comment
 * prefix, and shares it for the same reason they share the header:
 * copies of one sentence drift the moment one of them is corrected.
 */
const noEventsCommentFor = (commentPrefix: string): string =>
  `${commentPrefix} (no custom events declared yet)`;

const NO_EVENTS_COMMENT = noEventsCommentFor('//');

function renderLineCommentHeader({
  events,
  regenerateCommand,
  formatterHint,
  commentPrefix = '//',
}: LineCommentHeaderArgs): string {
  const c = commentPrefix;
  return [
    `${c} AUTO-GENERATED by @keewano/codegen.`,
    `${c} DO NOT EDIT. Re-run \`${regenerateCommand}\` to regenerate.`,
    `${c} Formatters and linters should skip it (${formatterHint}).`,
    c,
    `${c} ${EVENT_LIST_HEADING}`,
    renderEventList({ events, commentPrefix: c }),
  ].join('\n');
}

/** One line per event, so the file says which id belongs to which name. */
function renderEventList({
  events,
  commentPrefix,
}: {
  events: readonly ParsedEvent[];
  commentPrefix: string;
}): string {
  if (events.length === 0) return `${commentPrefix}   (no events defined)`;
  return events
    .map(
      (event) =>
        `${commentPrefix}   ${String(event.id)}  ${event.name}  ` +
        `(${CUSTOM_EVENT_TYPE_NAME_BY_TYPE[event.type]})`,
    )
    .join('\n');
}

export { EVENT_LIST_HEADING, NO_EVENTS_COMMENT, noEventsCommentFor, renderLineCommentHeader };
