/**
 * AUTO-GENERATED by @keewano/codegen.
 * DO NOT EDIT. Re-run `npx keewano-codegen --target expo --code <directory of this file>` to regenerate.
 * Formatters and linters should skip it (.prettierignore, .eslintignore).
 *
 * Events, in declaration order (id = 2500 + position):
 *   2500  Event00  (None)
 *   2501  Event01  (String)
 *   2502  Event02  (UnsignedInt)
 *   2503  Event03  (Bool)
 *   2504  Event04  (Timestamp)
 *   2505  Event05  (UnsignedShortVec2)
 *   2506  Event06  (PriceInUSDCents)
 *   2507  Event07  (None)
 *   2508  Event08  (String)
 *   2509  Event09  (UnsignedInt)
 */

import type { CustomEventSet } from '@keewano/react-native-expo-sdk';

import { Keewano } from '@keewano/react-native-expo-sdk';

export function reportEvent00(): void {
  Keewano.reportCustomEvent({ name: 'Event00' });
}

export function reportEvent01(value: string): void {
  Keewano.reportCustomEvent({ name: 'Event01', value });
}

export function reportEvent02(value: number): void {
  Keewano.reportCustomEvent({ name: 'Event02', value });
}

export function reportEvent03(value: boolean): void {
  Keewano.reportCustomEvent({ name: 'Event03', value });
}

export function reportEvent04(value: Date): void {
  Keewano.reportCustomEvent({ name: 'Event04', value });
}

export function reportEvent05(value: { x: number; y: number }): void {
  Keewano.reportCustomEvent({ name: 'Event05', value });
}

export function reportEvent06(value: number): void {
  Keewano.reportCustomEvent({ name: 'Event06', value });
}

export function reportEvent07(): void {
  Keewano.reportCustomEvent({ name: 'Event07' });
}

export function reportEvent08(value: string): void {
  Keewano.reportCustomEvent({ name: 'Event08', value });
}

export function reportEvent09(value: number): void {
  Keewano.reportCustomEvent({ name: 'Event09', value });
}

export const customEventSet: CustomEventSet = {
  version: 0xA426F500,
  eventCount: 10,
  gzipData: new Uint8Array([0x1F, 0x8B, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x35, 0xC6, 0xB7, 0x11, 0x80, 0x30, 0x00, 0x04, 0xC1, 0x93, 0x70, 0x43, 0x37, 0xC2, 0x09, 0xA9, 0x00, 0x4A, 0x21, 0x25, 0x62, 0xA8, 0x10, 0x6F, 0x7A, 0x22, 0xFA, 0x8D, 0x76, 0x2D, 0x8B, 0x61, 0x19, 0xA7, 0xD9, 0x39, 0xD8, 0xF4, 0xCA, 0xB0, 0xEB, 0xB5, 0xE5, 0xD0, 0x9B, 0x84, 0x53, 0x6F, 0x53, 0x2E, 0xBD, 0xCB, 0xB8, 0x75, 0x9F, 0xF3, 0xE8, 0x3D, 0xBC, 0x7A, 0x30, 0x7C, 0x7A, 0xB4, 0xFC, 0x74, 0xC6, 0x23, 0x6C, 0x78, 0x00, 0x00, 0x00]),
  events: [
    { id: 2500, name: 'Event00', type: 0 },
    { id: 2501, name: 'Event01', type: 1 },
    { id: 2502, name: 'Event02', type: 2 },
    { id: 2503, name: 'Event03', type: 3 },
    { id: 2504, name: 'Event04', type: 4 },
    { id: 2505, name: 'Event05', type: 5 },
    { id: 2506, name: 'Event06', type: 6 },
    { id: 2507, name: 'Event07', type: 0 },
    { id: 2508, name: 'Event08', type: 1 },
    { id: 2509, name: 'Event09', type: 2 },
  ],
};
