// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target kotlin --code <directory of this file> --asset <assets directory>` to regenerate.
// Formatters and linters should skip it (.editorconfig, detekt, ktlint).
//
// Events, in declaration order (id = 2500 + position):
//   2500  Event00  (None)
//   2501  Event01  (String)
//   2502  Event02  (UnsignedInt)
//   2503  Event03  (Bool)
//   2504  Event04  (Timestamp)
//   2505  Event05  (UnsignedShortVec2)
//   2506  Event06  (PriceInUSDCents)
//   2507  Event07  (None)
//   2508  Event08  (String)
//   2509  Event09  (UnsignedInt)

package com.keewano.sdk.generated

import com.keewano.sdk.KeewanoCodegen
import com.keewano.sdk.KeewanoSDK

fun KeewanoSDK.reportEvent00() = KeewanoCodegen.reportCustomEvent(2500)

fun KeewanoSDK.reportEvent01(value: String) = KeewanoCodegen.reportCustomEvent(2501, value)

fun KeewanoSDK.reportEvent02(value: Long) = KeewanoCodegen.reportCustomEvent(2502, value)

fun KeewanoSDK.reportEvent03(value: Boolean) = KeewanoCodegen.reportCustomEvent(2503, value)

fun KeewanoSDK.reportEvent04(value: Long) = KeewanoCodegen.reportCustomEvent(2504, value)

fun KeewanoSDK.reportEvent05(x: Int, y: Int) = KeewanoCodegen.reportCustomEventUShortPair(2505, x, y)

fun KeewanoSDK.reportEvent06(value: Long) = KeewanoCodegen.reportCustomEvent(2506, value)

fun KeewanoSDK.reportEvent07() = KeewanoCodegen.reportCustomEvent(2507)

fun KeewanoSDK.reportEvent08(value: String) = KeewanoCodegen.reportCustomEvent(2508, value)

fun KeewanoSDK.reportEvent09(value: Long) = KeewanoCodegen.reportCustomEvent(2509, value)
