# AUTO-GENERATED by @keewano/codegen.
# DO NOT EDIT. Re-run `keewano-codegen --target python --code <directory of this file>` to regenerate.
# Formatters and linters should skip it (black, ruff, flake8).
#
# Events, in declaration order (id = 2500 + position):
#   2500  Event00  (None)
#   2501  Event01  (String)
#   2502  Event02  (UnsignedInt)
#   2503  Event03  (Bool)
#   2504  Event04  (Timestamp)
#   2505  Event05  (UnsignedShortVec2)
#   2506  Event06  (PriceInUSDCents)
#   2507  Event07  (None)
#   2508  Event08  (String)
#   2509  Event09  (UnsignedInt)

from keewano_sdk import CustomEventSet, KeewanoCodegen

CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(
    version=2754016512,
    event_count=10,
    gzip_base64="H4sIAAAAAAAA/zXGtxGAMAAEwZNwQzfCCakASiElYqgQb3oi+o12LYthGafZOdj0yrDrteXQm4RTb1Muvcu4dZ/z6D28ejB8erT8dMYjbHgAAAA=",
)


def report_event00() -> None:
    KeewanoCodegen.report_custom_event(2500)


def report_event01(value: str) -> None:
    KeewanoCodegen.report_custom_event_str(2501, value)


def report_event02(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2502, value)


def report_event03(value: bool) -> None:
    KeewanoCodegen.report_custom_event_bool(2503, value)


def report_event04(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2504, value)


def report_event05(x: int, y: int) -> None:
    KeewanoCodegen.report_custom_event_ushort_pair(2505, x, y)


def report_event06(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2506, value)


def report_event07() -> None:
    KeewanoCodegen.report_custom_event(2507)


def report_event08(value: str) -> None:
    KeewanoCodegen.report_custom_event_str(2508, value)


def report_event09(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2509, value)
