// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target swift --code <directory of this file>` to regenerate.
// Formatters and linters should skip it (.swiftformat, .swiftlint.yml).
//
// Events, in declaration order (id = 2500 + position):
//   2500  Event00  (None)
//   2501  Event01  (String)
//   2502  Event02  (UnsignedInt)
//   2503  Event03  (Bool)
//   2504  Event04  (Timestamp)
//   2505  Event05  (UnsignedShortVec2)
//   2506  Event06  (PriceInUSDCents)
//   2507  Event07  (None)
//   2508  Event08  (String)
//   2509  Event09  (UnsignedInt)

import KeewanoSDK

public enum KeewanoCustomEvents {
    public static let set = KeewanoCustomEventSet(
        version: 2754016512,
        eventCount: 10,
        gzipBase64: "H4sIAAAAAAAA/zXGtxGAMAAEwZNwQzfCCakASiElYqgQb3oi+o12LYthGafZOdj0yrDrteXQm4RTb1Muvcu4dZ/z6D28ejB8erT8dMYjbHgAAAA="
    )
}

extension KeewanoSDK {
    public static func reportEvent00() {
        KeewanoCodegen.reportCustomEvent(2500)
    }

    public static func reportEvent01(_ value: String) {
        KeewanoCodegen.reportCustomEvent(2501, value)
    }

    public static func reportEvent02(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2502, value)
    }

    public static func reportEvent03(_ value: Bool) {
        KeewanoCodegen.reportCustomEvent(2503, value)
    }

    public static func reportEvent04(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2504, value)
    }

    public static func reportEvent05(x: Int, y: Int) {
        KeewanoCodegen.reportCustomEventUShortPair(2505, x, y)
    }

    public static func reportEvent06(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2506, value)
    }

    public static func reportEvent07() {
        KeewanoCodegen.reportCustomEvent(2507)
    }

    public static func reportEvent08(_ value: String) {
        KeewanoCodegen.reportCustomEvent(2508, value)
    }

    public static func reportEvent09(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2509, value)
    }
}
