/**
 * AUTO-GENERATED by @keewano/codegen.
 * DO NOT EDIT. Re-run `npx keewano-codegen --target expo --code <directory of this file>` to regenerate.
 * Formatters and linters should skip it (.prettierignore, .eslintignore).
 *
 * Events, in declaration order (id = 2500 + position):
 *   2500  A00  (String)
 *   2501  A10  (UnsignedInt)
 *   2502  A9  (Bool)
 *   2503  B00  (Timestamp)
 *   2504  X00  (UnsignedShortVec2)
 */

import type { CustomEventSet } from '@keewano/react-native-expo-sdk';

import { Keewano } from '@keewano/react-native-expo-sdk';

export function reportA00(value: string): void {
  Keewano.reportCustomEvent({ name: 'A00', value });
}

export function reportA10(value: number): void {
  Keewano.reportCustomEvent({ name: 'A10', value });
}

export function reportA9(value: boolean): void {
  Keewano.reportCustomEvent({ name: 'A9', value });
}

export function reportB00(value: Date): void {
  Keewano.reportCustomEvent({ name: 'B00', value });
}

export function reportX00(value: { x: number; y: number }): void {
  Keewano.reportCustomEvent({ name: 'X00', value });
}

export const customEventSet: CustomEventSet = {
  version: 0x0118E8C9,
  eventCount: 5,
  gzipData: new Uint8Array([0x1F, 0x8B, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x3B, 0xC2, 0xC9, 0xEC, 0x68, 0x60, 0xC0, 0xC8, 0x70, 0x14, 0x48, 0x1B, 0x1A, 0x30, 0x31, 0x1C, 0xE3, 0x64, 0x72, 0xB4, 0x64, 0x66, 0x38, 0xCE, 0xC9, 0xEC, 0x64, 0x60, 0xC0, 0xC2, 0x70, 0x82, 0x93, 0x39, 0xC2, 0xC0, 0x80, 0x95, 0x01, 0x00, 0xBF, 0xA6, 0x58, 0xF9, 0x27, 0x00, 0x00, 0x00]),
  events: [
    { id: 2500, name: 'A00', type: 1 },
    { id: 2501, name: 'A10', type: 2 },
    { id: 2502, name: 'A9', type: 3 },
    { id: 2503, name: 'B00', type: 4 },
    { id: 2504, name: 'X00', type: 5 },
  ],
};
