// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target kotlin --code <directory of this file> --asset <assets directory>` to regenerate.
// Formatters and linters should skip it (.editorconfig, detekt, ktlint).
//
// Events, in declaration order (id = 2500 + position):
//   2500  A00  (String)
//   2501  A10  (UnsignedInt)
//   2502  A9  (Bool)
//   2503  B00  (Timestamp)
//   2504  X00  (UnsignedShortVec2)

package com.keewano.sdk.generated

import com.keewano.sdk.KeewanoCodegen
import com.keewano.sdk.KeewanoSDK

fun KeewanoSDK.reportA00(value: String) = KeewanoCodegen.reportCustomEvent(2500, value)

fun KeewanoSDK.reportA10(value: Long) = KeewanoCodegen.reportCustomEvent(2501, value)

fun KeewanoSDK.reportA9(value: Boolean) = KeewanoCodegen.reportCustomEvent(2502, value)

fun KeewanoSDK.reportB00(value: Long) = KeewanoCodegen.reportCustomEvent(2503, value)

fun KeewanoSDK.reportX00(x: Int, y: Int) = KeewanoCodegen.reportCustomEventUShortPair(2504, x, y)
