# AUTO-GENERATED by @keewano/codegen.
# DO NOT EDIT. Re-run `keewano-codegen --target python --code <directory of this file>` to regenerate.
# Formatters and linters should skip it (black, ruff, flake8).
#
# Events, in declaration order (id = 2500 + position):
#   2500  A00  (String)
#   2501  A10  (UnsignedInt)
#   2502  A9  (Bool)
#   2503  B00  (Timestamp)
#   2504  X00  (UnsignedShortVec2)

from keewano_sdk import CustomEventSet, KeewanoCodegen

CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(
    version=18409673,
    event_count=5,
    gzip_base64="H4sIAAAAAAAA/zvCyexoYMDIcBRIGxowMRzjZHK0ZGY4zsnsZGDAwnCCkznCwICVAQC/plj5JwAAAA==",
)


def report_a00(value: str) -> None:
    KeewanoCodegen.report_custom_event_str(2500, value)


def report_a10(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2501, value)


def report_a9(value: bool) -> None:
    KeewanoCodegen.report_custom_event_bool(2502, value)


def report_b00(value: int) -> None:
    KeewanoCodegen.report_custom_event_uint(2503, value)


def report_x00(x: int, y: int) -> None:
    KeewanoCodegen.report_custom_event_ushort_pair(2504, x, y)
