// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target swift --code <directory of this file>` to regenerate.
// Formatters and linters should skip it (.swiftformat, .swiftlint.yml).
//
// Events, in declaration order (id = 2500 + position):
//   2500  A00  (String)
//   2501  A10  (UnsignedInt)
//   2502  A9  (Bool)
//   2503  B00  (Timestamp)
//   2504  X00  (UnsignedShortVec2)

import KeewanoSDK

public enum KeewanoCustomEvents {
    public static let set = KeewanoCustomEventSet(
        version: 18409673,
        eventCount: 5,
        gzipBase64: "H4sIAAAAAAAA/zvCyexoYMDIcBRIGxowMRzjZHK0ZGY4zsnsZGDAwnCCkznCwICVAQC/plj5JwAAAA=="
    )
}

extension KeewanoSDK {
    public static func reportA00(_ value: String) {
        KeewanoCodegen.reportCustomEvent(2500, value)
    }

    public static func reportA10(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2501, value)
    }

    public static func reportA9(_ value: Bool) {
        KeewanoCodegen.reportCustomEvent(2502, value)
    }

    public static func reportB00(_ value: Int64) {
        KeewanoCodegen.reportCustomEvent(2503, value)
    }

    public static func reportX00(x: Int, y: Int) {
        KeewanoCodegen.reportCustomEventUShortPair(2504, x, y)
    }
}
