// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target kotlin --code <directory of this file> --asset <assets directory>` to regenerate.
// Formatters and linters should skip it (.editorconfig, detekt, ktlint).
//
// Events, in declaration order (id = 2500 + position):
//   (no events defined)

package com.keewano.sdk.generated

// (no custom events declared yet)
