# AUTO-GENERATED by @keewano/codegen.
# DO NOT EDIT. Re-run `keewano-codegen --target python --code <directory of this file>` to regenerate.
# Formatters and linters should skip it (black, ruff, flake8).
#
# Events, in declaration order (id = 2500 + position):
#   (no events defined)

from keewano_sdk import CustomEventSet

CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(
    version=0,
    event_count=0,
    gzip_base64="",
)


# (no custom events declared yet)
