/**
 * AUTO-GENERATED by @keewano/codegen.
 * DO NOT EDIT. Re-run `npx keewano-codegen --target react-native --code <directory of this file>` to regenerate.
 * Formatters and linters should skip it (.prettierignore, .eslintignore).
 *
 * Events, in declaration order (id = 2500 + position):
 *   (no events defined)
 */

import type { CustomEventSet } from '@keewano/react-native-sdk';

// (no custom events declared yet)

export const customEventSet: CustomEventSet = {
  version: 0x00000000,
  eventCount: 0,
  gzipData: new Uint8Array([]),
  events: [],
};
