// AUTO-GENERATED by @keewano/codegen.
// DO NOT EDIT. Re-run `keewano-codegen --target swift --code <directory of this file>` to regenerate.
// Formatters and linters should skip it (.swiftformat, .swiftlint.yml).
//
// Events, in declaration order (id = 2500 + position):
//   (no events defined)

import KeewanoSDK

public enum KeewanoCustomEvents {
    public static let set = KeewanoCustomEventSet(
        version: 0,
        eventCount: 0,
        gzipBase64: ""
    )
}

// (no custom events declared yet)
